apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mariadb-credentials
  namespace: default
  labels:
    app: guitartortona-api
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: mariadb-credentials
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: secret/guitartortona/production/mariadb
      property: username
  - secretKey: password
    remoteRef:
      key: secret/guitartortona/production/mariadb
      property: password
